FROM mcr.microsoft.com/playwright:v1.58.2-noble
WORKDIR /app

# Copy everything (except what's in .dockerignore)
COPY . .

# Manually install dependencies for both projects
RUN cd frontEnd && npm install
RUN cd backEnd && npm install

# Install Playwright browsers specifically
RUN npx playwright install --with-deps