name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Backend Tests
        run: cd backEnd && npm run test

      - name: Run Frontend Tests
        run: cd frontEnd && npm run test

      - name: Run E2E Tests
        run: npx playwright test
